# Generated by Django 5.1.1 on 2024-09-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='states',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('districtid', models.AutoField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.states')),
            ],
        ),
    ]
