# Generated by Django 5.1.1 on 2024-10-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='affiliates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliatesname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/')),
                ('affiliateslink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='annualreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualdescription', models.TextField()),
                ('annualbrochure', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='boardmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('affliation', models.CharField(max_length=50)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('image', models.ImageField(upload_to='image/')),
                ('twitter', models.CharField(max_length=50)),
                ('ORCID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bylawtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='eventtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventtypename', models.CharField(max_length=100)),
                ('eventtypedescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionname', models.CharField(max_length=100)),
                ('institutionlink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='membershiptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershiptypename', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('eventdate', models.DateField()),
                ('eventtime', models.CharField(max_length=50)),
                ('eventplace', models.CharField(max_length=50)),
                ('eventdescription', models.TextField()),
                ('eventbrochure', models.ImageField(upload_to='image/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.states')),
                ('eventtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='membershipsubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('membershiptypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('Linkedln', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('ORCID', models.BigIntegerField()),
                ('registereddate', models.DateTimeField()),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.affiliates')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.states')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.subscribe')),
            ],
        ),
    ]
