# Generated by Django 5.1.2 on 2024-10-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_membershiptypeid_membershipsubscription_membershiptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.signup')),
                ('membershiptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.membershiptype')),
            ],
        ),
    ]
