# Generated by Django 5.1.2 on 2024-11-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('countryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='Linkedln',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='ORCID',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='lastname',
        ),
        migrations.AddField(
            model_name='signup',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.country'),
            preserve_default=False,
        ),
    ]
