# Generated by Django 5.1.3 on 2024-11-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_country_remove_signup_linkedln_remove_signup_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='institution',
            name='districts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='library',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
