# Generated by Django 5.1.3 on 2024-11-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_remove_signup_affiliation_institution_districts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='countrys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.states'),
            preserve_default=False,
        ),
    ]
